### ISSUE TITLE
Migrate from /uuid to /content/uuid

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#858]
## TODO

- [x] update service registry
- [x] make sure to [update `/__access_metadata` to include](https://github.com/Financial-Times/next-access-metadata/blob/master/data/__access_metadata.json) the new URL schema so we don't give allll the content away for free.
- [x] update access gate head endpoint 
- [x] implement redirects in the [next redirector service](https://github.com/Financial-Times/next-redirector) from old style to new style
- [x] put notes on components that rely on /8-4-4-12 routes to update to /content/whatevs
